/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Applicant'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Applicant'));
  } else {
    // Browser globals (root is window)
    if (!root.Onfido) {
      root.Onfido = {};
    }
    root.Onfido.ApplicantsList = factory(root.Onfido.ApiClient, root.Onfido.Applicant);
  }
}(this, function(ApiClient, Applicant) {
  'use strict';



  /**
   * The ApplicantsList model module.
   * @module model/ApplicantsList
   * @version 3.1.0
   */

  /**
   * Constructs a new <code>ApplicantsList</code>.
   * @alias module:model/ApplicantsList
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>ApplicantsList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApplicantsList} obj Optional instance to populate.
   * @return {module:model/ApplicantsList} The populated <code>ApplicantsList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('applicants')) {
        obj['applicants'] = ApiClient.convertToType(data['applicants'], [Applicant]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Applicant>} applicants
   */
  exports.prototype['applicants'] = undefined;


  /**
   * @return {Array.<module:model/Applicant>}
   */
  exports.prototype.getApplicants = function() {
    return this['applicants'];
  }

  /**
   * @param {Array.<module:model/Applicant>} applicants
   */
  exports.prototype.setApplicants = function(applicants) {
    this['applicants'] = applicants;
  }



  return exports;
}));


