/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LivePhoto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LivePhoto'));
  } else {
    // Browser globals (root is window)
    if (!root.Onfido) {
      root.Onfido = {};
    }
    root.Onfido.LivePhotosList = factory(root.Onfido.ApiClient, root.Onfido.LivePhoto);
  }
}(this, function(ApiClient, LivePhoto) {
  'use strict';



  /**
   * The LivePhotosList model module.
   * @module model/LivePhotosList
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>LivePhotosList</code>.
   * @alias module:model/LivePhotosList
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>LivePhotosList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LivePhotosList} obj Optional instance to populate.
   * @return {module:model/LivePhotosList} The populated <code>LivePhotosList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('live_photos')) {
        obj['live_photos'] = ApiClient.convertToType(data['live_photos'], [LivePhoto]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/LivePhoto>} live_photos
   */
  exports.prototype['live_photos'] = undefined;


  /**
   * @return {Array.<module:model/LivePhoto>}
   */
  exports.prototype.getLivePhotos = function() {
    return this['live_photos'];
  }

  /**
   * @param {Array.<module:model/LivePhoto>} live_photos
   */
  exports.prototype.setLivePhotos = function(live_photos) {
    this['live_photos'] = live_photos;
  }



  return exports;
}));


