/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Onfido) {
      root.Onfido = {};
    }
    root.Onfido.SdkTokenResponse = factory(root.Onfido.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The SdkTokenResponse model module.
   * @module model/SdkTokenResponse
   * @version 4.3.0
   */

  /**
   * Constructs a new <code>SdkTokenResponse</code>.
   * @alias module:model/SdkTokenResponse
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>SdkTokenResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SdkTokenResponse} obj Optional instance to populate.
   * @return {module:model/SdkTokenResponse} The populated <code>SdkTokenResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('token')) {
        obj['token'] = ApiClient.convertToType(data['token'], 'String');
      }
    }
    return obj;
  }

  /**
   * The generated SDK token
   * @member {String} token
   */
  exports.prototype['token'] = undefined;


  /**
   * Returns The generated SDK token
   * @return {String}
   */
  exports.prototype.getToken = function() {
    return this['token'];
  }

  /**
   * Sets The generated SDK token
   * @param {String} token The generated SDK token
   */
  exports.prototype.setToken = function(token) {
    this['token'] = token;
  }



  return exports;
}));


