/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Onfido) {
      root.Onfido = {};
    }
    root.Onfido.SdkTokenRequest = factory(root.Onfido.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The SdkTokenRequest model module.
   * @module model/SdkTokenRequest
   * @version 4.3.0
   */

  /**
   * Constructs a new <code>SdkTokenRequest</code>.
   * @alias module:model/SdkTokenRequest
   * @class
   * @param applicant_id {String} The unique identifier of the applicant
   */
  var exports = function(applicant_id) {
    var _this = this;

    _this['applicant_id'] = applicant_id;
  };

  /**
   * Constructs a <code>SdkTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SdkTokenRequest} obj Optional instance to populate.
   * @return {module:model/SdkTokenRequest} The populated <code>SdkTokenRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('applicant_id')) {
        obj['applicant_id'] = ApiClient.convertToType(data['applicant_id'], 'String');
      }
      if (data.hasOwnProperty('referrer')) {
        obj['referrer'] = ApiClient.convertToType(data['referrer'], 'String');
      }
      if (data.hasOwnProperty('application_id')) {
        obj['application_id'] = ApiClient.convertToType(data['application_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * The unique identifier of the applicant
   * @member {String} applicant_id
   */
  exports.prototype['applicant_id'] = undefined;
  /**
   * The referrer URL pattern
   * @member {String} referrer
   */
  exports.prototype['referrer'] = undefined;
  /**
   * The application ID (iOS or Android)
   * @member {String} application_id
   */
  exports.prototype['application_id'] = undefined;


  /**
   * Returns The unique identifier of the applicant
   * @return {String}
   */
  exports.prototype.getApplicantId = function() {
    return this['applicant_id'];
  }

  /**
   * Sets The unique identifier of the applicant
   * @param {String} applicant_id The unique identifier of the applicant
   */
  exports.prototype.setApplicantId = function(applicant_id) {
    this['applicant_id'] = applicant_id;
  }


  /**
   * Returns The referrer URL pattern
   * @return {String}
   */
  exports.prototype.getReferrer = function() {
    return this['referrer'];
  }

  /**
   * Sets The referrer URL pattern
   * @param {String} referrer The referrer URL pattern
   */
  exports.prototype.setReferrer = function(referrer) {
    this['referrer'] = referrer;
  }


  /**
   * Returns The application ID (iOS or Android)
   * @return {String}
   */
  exports.prototype.getApplicationId = function() {
    return this['application_id'];
  }

  /**
   * Sets The application ID (iOS or Android)
   * @param {String} application_id The application ID (iOS or Android)
   */
  exports.prototype.setApplicationId = function(application_id) {
    this['application_id'] = application_id;
  }



  return exports;
}));


