/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Webhook'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Webhook'));
  } else {
    // Browser globals (root is window)
    if (!root.Onfido) {
      root.Onfido = {};
    }
    root.Onfido.WebhooksList = factory(root.Onfido.ApiClient, root.Onfido.Webhook);
  }
}(this, function(ApiClient, Webhook) {
  'use strict';



  /**
   * The WebhooksList model module.
   * @module model/WebhooksList
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>WebhooksList</code>.
   * @alias module:model/WebhooksList
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>WebhooksList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhooksList} obj Optional instance to populate.
   * @return {module:model/WebhooksList} The populated <code>WebhooksList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('webhooks')) {
        obj['webhooks'] = ApiClient.convertToType(data['webhooks'], [Webhook]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Webhook>} webhooks
   */
  exports.prototype['webhooks'] = undefined;


  /**
   * @return {Array.<module:model/Webhook>}
   */
  exports.prototype.getWebhooks = function() {
    return this['webhooks'];
  }

  /**
   * @param {Array.<module:model/Webhook>} webhooks
   */
  exports.prototype.setWebhooks = function(webhooks) {
    this['webhooks'] = webhooks;
  }



  return exports;
}));


