/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Onfido);
  }
}(this, function(expect, Onfido) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Onfido.Applicant();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Applicant', function() {
    it('should create an instance of Applicant', function() {
      // uncomment below and update the code to test Applicant
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be.a(Onfido.Applicant);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property created_at (base name: "created_at")', function() {
      // uncomment below and update the code to test the property created_at
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property delete_at (base name: "delete_at")', function() {
      // uncomment below and update the code to test the property delete_at
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property href (base name: "href")', function() {
      // uncomment below and update the code to test the property href
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property sandbox (base name: "sandbox")', function() {
      // uncomment below and update the code to test the property sandbox
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property first_name (base name: "first_name")', function() {
      // uncomment below and update the code to test the property first_name
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property middle_name (base name: "middle_name")', function() {
      // uncomment below and update the code to test the property middle_name
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property last_name (base name: "last_name")', function() {
      // uncomment below and update the code to test the property last_name
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property dob (base name: "dob")', function() {
      // uncomment below and update the code to test the property dob
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property telephone (base name: "telephone")', function() {
      // uncomment below and update the code to test the property telephone
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property mobile (base name: "mobile")', function() {
      // uncomment below and update the code to test the property mobile
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property nationality (base name: "nationality")', function() {
      // uncomment below and update the code to test the property nationality
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property mothers_maiden_name (base name: "mothers_maiden_name")', function() {
      // uncomment below and update the code to test the property mothers_maiden_name
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property country_of_birth (base name: "country_of_birth")', function() {
      // uncomment below and update the code to test the property country_of_birth
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property town_of_birth (base name: "town_of_birth")', function() {
      // uncomment below and update the code to test the property town_of_birth
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property previous_last_name (base name: "previous_last_name")', function() {
      // uncomment below and update the code to test the property previous_last_name
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property addresses (base name: "addresses")', function() {
      // uncomment below and update the code to test the property addresses
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

    it('should have the property id_numbers (base name: "id_numbers")', function() {
      // uncomment below and update the code to test the property id_numbers
      //var instance = new Onfido.Applicant();
      //expect(instance).to.be();
    });

  });

}));
