/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Onfido);
  }
}(this, function(expect, Onfido) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Onfido.Document();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Document', function() {
    it('should create an instance of Document', function() {
      // uncomment below and update the code to test Document
      //var instance = new Onfido.Document();
      //expect(instance).to.be.a(Onfido.Document);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Onfido.Document();
      //expect(instance).to.be();
    });

    it('should have the property created_at (base name: "created_at")', function() {
      // uncomment below and update the code to test the property created_at
      //var instance = new Onfido.Document();
      //expect(instance).to.be();
    });

    it('should have the property file_name (base name: "file_name")', function() {
      // uncomment below and update the code to test the property file_name
      //var instance = new Onfido.Document();
      //expect(instance).to.be();
    });

    it('should have the property file_size (base name: "file_size")', function() {
      // uncomment below and update the code to test the property file_size
      //var instance = new Onfido.Document();
      //expect(instance).to.be();
    });

    it('should have the property file_type (base name: "file_type")', function() {
      // uncomment below and update the code to test the property file_type
      //var instance = new Onfido.Document();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Onfido.Document();
      //expect(instance).to.be();
    });

    it('should have the property side (base name: "side")', function() {
      // uncomment below and update the code to test the property side
      //var instance = new Onfido.Document();
      //expect(instance).to.be();
    });

    it('should have the property href (base name: "href")', function() {
      // uncomment below and update the code to test the property href
      //var instance = new Onfido.Document();
      //expect(instance).to.be();
    });

    it('should have the property download_href (base name: "download_href")', function() {
      // uncomment below and update the code to test the property download_href
      //var instance = new Onfido.Document();
      //expect(instance).to.be();
    });

  });

}));
