/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Onfido);
  }
}(this, function(expect, Onfido) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Onfido.GenericAddress();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GenericAddress', function() {
    it('should create an instance of GenericAddress', function() {
      // uncomment below and update the code to test GenericAddress
      //var instane = new Onfido.GenericAddress();
      //expect(instance).to.be.a(Onfido.GenericAddress);
    });

    it('should have the property flatNumber (base name: "flat_number")', function() {
      // uncomment below and update the code to test the property flatNumber
      //var instane = new Onfido.GenericAddress();
      //expect(instance).to.be();
    });

    it('should have the property buildingNumber (base name: "building_number")', function() {
      // uncomment below and update the code to test the property buildingNumber
      //var instane = new Onfido.GenericAddress();
      //expect(instance).to.be();
    });

    it('should have the property buildingName (base name: "building_name")', function() {
      // uncomment below and update the code to test the property buildingName
      //var instane = new Onfido.GenericAddress();
      //expect(instance).to.be();
    });

    it('should have the property street (base name: "street")', function() {
      // uncomment below and update the code to test the property street
      //var instane = new Onfido.GenericAddress();
      //expect(instance).to.be();
    });

    it('should have the property subStreet (base name: "sub_street")', function() {
      // uncomment below and update the code to test the property subStreet
      //var instane = new Onfido.GenericAddress();
      //expect(instance).to.be();
    });

    it('should have the property town (base name: "town")', function() {
      // uncomment below and update the code to test the property town
      //var instane = new Onfido.GenericAddress();
      //expect(instance).to.be();
    });

    it('should have the property postcode (base name: "postcode")', function() {
      // uncomment below and update the code to test the property postcode
      //var instane = new Onfido.GenericAddress();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instane = new Onfido.GenericAddress();
      //expect(instance).to.be();
    });

  });

}));
