/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Onfido);
  }
}(this, function(expect, Onfido) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Onfido.SdkTokenRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SdkTokenRequest', function() {
    it('should create an instance of SdkTokenRequest', function() {
      // uncomment below and update the code to test SdkTokenRequest
      //var instance = new Onfido.SdkTokenRequest();
      //expect(instance).to.be.a(Onfido.SdkTokenRequest);
    });

    it('should have the property applicant_id (base name: "applicant_id")', function() {
      // uncomment below and update the code to test the property applicant_id
      //var instance = new Onfido.SdkTokenRequest();
      //expect(instance).to.be();
    });

    it('should have the property referrer (base name: "referrer")', function() {
      // uncomment below and update the code to test the property referrer
      //var instance = new Onfido.SdkTokenRequest();
      //expect(instance).to.be();
    });

    it('should have the property application_id (base name: "application_id")', function() {
      // uncomment below and update the code to test the property application_id
      //var instance = new Onfido.SdkTokenRequest();
      //expect(instance).to.be();
    });

  });

}));
